# Generated by Django 2.2.7 on 2020-08-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_origin_url', models.TextField()),
                ('ip_address', models.TextField(null=True)),
                ('session_id', models.TextField()),
                ('event_name', models.TextField()),
                ('time_stamp', models.DateTimeField()),
                ('text', models.TextField()),
                ('chat_source_latitude', models.TextField()),
                ('chat_source_longitude', models.TextField()),
                ('browser', models.TextField()),
                ('update_date_time', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.Bots')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.Customers')),
            ],
        ),
        migrations.AddField(
            model_name='bots',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.Customers'),
        ),
        migrations.CreateModel(
            name='BotQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=500, null=True)),
                ('question_id', models.IntegerField()),
                ('answer_type', models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('RADIO', 'RADIO'), ('DROPDOWN', 'DROPDOWN'), ('CHECKBOX', 'CHECKBOX'), ('FILE', 'FILE'), ('DATE', 'DATE')], max_length=10)),
                ('suggested_answers', models.TextField(default=[])),
                ('suggested_jump', models.TextField(default=[])),
                ('validation1', models.TextField(default='')),
                ('validation2', models.TextField(default='')),
                ('error_msg', models.TextField(default='')),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('required', models.CharField(default='no', max_length=4)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.Bots')),
            ],
            options={
                'db_table': 'ChatBot_client_questions',
            },
        ),
    ]
