# Generated by Django 2.2.7 on 2020-08-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=500, null=True)),
                ('question_id', models.IntegerField()),
                ('answer_type', models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('RADIO', 'RADIO'), ('DROPDOWN', 'DROPDOWN'), ('CHECKBOX', 'CHECKBOX'), ('FILE', 'FILE'), ('DATE', 'DATE')], max_length=10)),
                ('suggested_answers', models.TextField(default=[])),
                ('suggested_jump', models.TextField(default=[])),
                ('validation1', models.TextField(default='')),
                ('validation2', models.TextField(default='')),
                ('error_msg', models.TextField(default='')),
                ('created_by_id', models.IntegerField()),
                ('updated_by_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('required', models.CharField(default='no', max_length=4)),
            ],
            options={
                'db_table': 'ChatBot_client_questions',
            },
        ),
    ]
