# Generated by Django 3.1 on 2020-09-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
                ('model_name', models.CharField(max_length=125, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(null=True)),
                ('updated_by_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_name', models.CharField(max_length=100, unique=True)),
                ('web_url', models.TextField(unique=True)),
                ('email_id', models.EmailField(max_length=200, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('date_joined', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(null=True)),
                ('updated_by_id', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('logo_path', models.TextField(default='static/images/default/org_logo.png')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id_text', models.TextField(max_length=100, unique=True)),
                ('bot_id_text', models.TextField(max_length=150)),
                ('source_url', models.TextField()),
                ('bot_type', models.CharField(choices=[('BASIC', 'BASIC'), ('POWER', 'POWER')], max_length=6)),
                ('header_colour', models.CharField(default='header_colour', max_length=25)),
                ('body_colour', models.CharField(default='body_colour', max_length=25)),
                ('font_type', models.CharField(default='font_type', max_length=25)),
                ('bot_logo', models.TextField(default='static/images/default/bot_logo.png')),
                ('chat_logo', models.TextField(default='static/images/default/chat_logo.png')),
                ('user_logo', models.TextField(default='static/images/default/user_logo.png')),
                ('bot_bubble_colour', models.CharField(default='bot_bubble_colour', max_length=25)),
                ('user_bubble_colour', models.CharField(default='user_bubble_colour', max_length=25)),
                ('chat_bot_font_colour', models.CharField(default='chat_bot_font_colour', max_length=25)),
                ('chat_user_font_colour', models.CharField(default='chat_user_font_colour', max_length=25)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(null=True)),
                ('updated_by_id', models.IntegerField(null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.bots')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.customers')),
            ],
            options={
                'db_table': 'ChatBot_customer_bots',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_origin_url', models.TextField()),
                ('ip_address', models.TextField(null=True)),
                ('session_id', models.TextField()),
                ('event_name', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('sender', models.CharField(max_length=10)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('browser', models.TextField(null=True)),
                ('update_date_time', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.bots')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.customers')),
            ],
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=500, null=True)),
                ('question_id', models.IntegerField()),
                ('answer_type', models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('RADIO', 'RADIO'), ('DROPDOWN', 'DROPDOWN'), ('CHECKBOX', 'CHECKBOX'), ('FILE', 'FILE'), ('DATE', 'DATE')], max_length=10)),
                ('suggested_answers', models.TextField(default=[])),
                ('suggested_jump', models.TextField(default=[])),
                ('validation1', models.TextField(default='')),
                ('validation2', models.TextField(default='')),
                ('error_msg', models.TextField(default='')),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('required', models.CharField(default='no', max_length=4)),
                ('related', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.bots')),
            ],
            options={
                'db_table': 'ChatBot_client_questions',
            },
        ),
    ]
