# Generated by Django 3.1 on 2020-09-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ChatBot.customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='is_last_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='is_lead_gen_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='body_colour',
            field=models.CharField(default='#FFFFFFF', max_length=25),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='bot_bubble_colour',
            field=models.CharField(default='#C0C0C0', max_length=25),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='chat_bot_font_colour',
            field=models.CharField(default='#000000', max_length=25),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='chat_logo',
            field=models.TextField(default='static/images/default/chat.png'),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='chat_user_font_colour',
            field=models.CharField(default='#FFFFFF', max_length=25),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='font_type',
            field=models.CharField(default='Arial, Helvitica', max_length=25),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='header_colour',
            field=models.CharField(default='#000000', max_length=25),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='user_bubble_colour',
            field=models.CharField(default='#606060', max_length=25),
        ),
        migrations.AlterField(
            model_name='customerbots',
            name='user_logo',
            field=models.TextField(default='static/images/default/user_logo.jpg'),
        ),
    ]
