# Generated by Django 2.2.7 on 2020-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0002_auto_20200811_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='botquestions',
            name='related',
            field=models.BooleanField(default=False),
        ),
    ]
