# Generated by Django 3.1 on 2020-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0002_auto_20200913_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('token', models.TextField(blank=True, null=True)),
                ('token_expired', models.DateTimeField(blank=True, null=True)),
                ('is_password_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customers',
            name='is_password_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='token_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
