# Generated by Django 3.1 on 2020-10-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0004_auto_20200928_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.TextField()),
                ('context', models.TextField()),
                ('recipient', models.TextField()),
                ('subject', models.TextField()),
                ('status', models.TextField()),
                ('created_by_id', models.IntegerField()),
                ('updated_by_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ChatBot_email_status',
            },
        ),
    ]
