# Generated by Django 3.1 on 2020-08-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0005_auto_20200824_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chat_source_latitude',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='chat_source_longitude',
        ),
        migrations.AddField(
            model_name='conversation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
