# Generated by Django 3.1 on 2020-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0005_emailstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='is_first_question',
            field=models.BooleanField(default=False),
        ),
    ]
