# Generated by Django 3.1 on 2020-08-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0006_auto_20200825_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_id',
            new_name='CustomerID',
        ),
    ]
