# Generated by Django 3.1 on 2020-10-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0006_botconfiguration_is_first_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbots',
            name='for_whole_site',
            field=models.BooleanField(default=False),
        ),
    ]
