# Generated by Django 3.1 on 2020-08-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0007_auto_20200826_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='email_id',
            new_name='email',
        ),
    ]
