# Generated by Django 3.1 on 2020-08-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0009_auto_20200826_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
