# Generated by Django 3.1 on 2020-08-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0011_auto_20200826_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='latitude',
            new_name='chat_source_latitude',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
    ]
