# Generated by Django 3.1 on 2020-08-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0012_auto_20200826_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_source_longitude',
            field=models.FloatField(null=True),
        ),
    ]
