# Generated by Django 3.1 on 2020-08-25 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0013_conversation_chat_source_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='chat_source_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='chat_source_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='CustomerID',
            new_name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender',
            field=models.CharField(default='me', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='email_id',
            field=models.EmailField(default='admin@chemstride.com', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 1, 36, 28, 686299)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='mobile',
            field=models.BigIntegerField(default=8989898989, unique=True),
            preserve_default=False,
        ),
    ]
